### ISSUE TITLE
Flathub export

### ISSUE THREAD

**Issue by vendillah** [phastmike/tags#48]
The app looks useful! Are there any plans to export it to Flathub? It would make it easier to keep up to date with all the apps and perhaps make it more public, instead of checking each for an update through their repositories. There is an unfortunate name clash with [Tagger](https://flathub.org/apps/org.nickvision.tagger) for music tagging though. Perhaps rename to Log/Rule/Line Tagger just to avoid confusion? (Just some ideas, but I believe you can use the same name.)

**Comment by phastmike** [comment]
Hi @vendillah Thank you for feedback. I've been thinking of it and reading a bit on the process.  Regarding the name clash, indeed there is and I'm also thinking about that, nevertheless there's no problem on using the same name. Let's see :) 

Thank you for creating the issue.

Best regards

**Comment by phastmike** [comment]
@vendillah you can try it, just went live on flathub:

https://flathub.org/apps/io.github.phastmike.tags

**Comment by vendillah** [comment]
@phastmike, that's exactly what I ~~'ll be doing~~ did! :-) Thanks for the heads up.

At the moment I don't need it for some certain thing (though I did back then shortly!), but I tried it on `/etc/services` as to give you feedback, since I'm grateful I now have a log-inspecting application available . (I don't know however exactly what programs the file is managed by and my potential use-cases and evaluations may not make sense.)
 
- I noticed: I didn't find the file name quickly, but that's because I didn't remember what I had opened and "services" had no extension. (So, perhaps not too valuable as feedback.)
- I tried tags with patterns "asa", "tcp" and "https".
  - It would be nice if upon creation, automatically a new color would be proposed, even if it's just another tint of green. At the moment, the suggested color is probably a default green color (which ensures contrast of course).
  - I can disable tags, which is very useful. I can imagine that it would be nice if I were also able to simply _hide_ certain log messages (such log-clutter.) ("Apply tag as filter".) Do mind however that the UI of this should clearly state that they are hidden. If you were to add another check box for that next to the current, that would be convenient, but confusing.
- A lot of basic functionality that a user could expect is present, such as clicking on a tag and opening a modify window. Or clicking on a tag in the file. Even dragging to reorder the tags, well done! Also, for the few minutes I tested I didn't encounter any bugs. In my opinion, the application feels mature enough for release, so version 1.0 was well chosen. Here are some details:
  - When you press the new tag button (the left of the split button near the top right corner), a window opens to create a new tag. A small thing I noticed: I can't cancel when pressing ESC - it would be nice.
  - When you modify an existing tag, you apply it with "Edit". I would expect that word to open up an edit screen. As given away by my wording, I would use the word "Apply" instead.
- Maybe this is more of a nice to have, but would it be useful to display the coverage (i.e. the percentage or count, or both) of a tag? 
- Another idea is: right mouse click to select "create filter from text" which already fills in the text in the pattern. This may get annoying when the line is very long, but up to the user to decide if they use it. Alternatively, you could allow selection of lines, so that one can select a pattern, then right mouse click the selection and put the selected text in the pattern.
 
I am somewhat a gnome fan and testing out new adwaita/gtk applications now and then, so I don't _really_ need it currently. They are just propositions on what you could work on if you'd wonder what users (such as myself) would find interesting. I recently started working on a typing application in Vala either, and by searching other Vala+Gtk applications I found yours.  I'm not as far though :p Goodluck!

**Comment by phastmike** [comment]
Hi @vendillah Thank you for the feedback :) It was something that I was aiming for some time and finally did it.

Maybe a some context about why I've decided to make the app. I analyze a bunch of system logs regularly and there some applications that help at this but all have different approaches. I liked TextAnalysisTool.NET but it is window only. As I have some background dealing with Gtk I could imagine a simple approach and reach the some behavior easily with the added bonus of adapting it to my needs. That's the reasoning behind the app.

So trying to answer your suggestions:

- _It would be nice if upon creation, automatically a new color would be proposed, even if it's just another tint of green. At the moment, the suggested color is probably a default green color (which ensures contrast of course)._

   I had, since the beginning, the intention of having managed user defined color schemes but normally I tend to use only a few tags and left that for a future implementation. The idea of a different color on every tag is a nice catch. I'll look into it, Thank you ;)

- _I can disable tags, which is very useful. I can imagine that it would be nice if I were also able to simply hide certain log messages (such log-clutter.) ("Apply tag as filter".) Do mind however that the UI of this should clearly state that they are hidden. If you were to add another check box for that next to the current, that would be convenient, but confusing._

   There are also keyboard shortcuts for tag enabling/disabling and Soloing, rather limited to the first 10 tags and hardcoded to the tag sequence. I also thought about hide tags but not sure exactly how to apply it. What I tend to do, is tagging lines of interest on a wider filter or filters and then save tagged lines which will remove untagged lines and then open the saved/exported/resulting file. As soon as I get a good behavior for hiding lines it may be implemented. 

- _When you press the new tag button (the left of the split button near the top right corner), a window opens to create a new tag. A small thing I noticed: I can't cancel when pressing ESC - it would be nice._

   That's a nice suggestion. I'll work on that.    

- _When you modify an existing tag, you apply it with "Edit". I would expect that word to open up an edit screen. As given away by my wording, I would use the word "Apply" instead._

   This has been something that is recommended in the GNOME HIG (Human Interface Guidelines), or at least it was. Using verbs for the action instead of the generic Ok/Apply Cancel. More info can here: https://developer.gnome.org/hig/patterns/feedback/dialogs.html nonetheless I'll take that into account ;)

- _Maybe this is more of a nice to have, but would it be useful to display the coverage (i.e. the percentage or count, or both) of a tag?_

   At the moment there's the hit count which for me it's more useful but maybe we can have this in the preferences and have hit count as a number or percentage (eventually both)

- _Another idea is: right mouse click to select "create filter from text" which already fills in the text in the pattern. This may get annoying when the line is very long, but up to the user to decide if they use it. Alternatively, you could allow selection of lines, so that one can select a pattern, then right mouse click the selection and put the selected text in the pattern._

   You don't need right click, just double click on a line and a dialog to create a tag with the tag pattern filled out should show up :). The selection of text may be something to implement when I move away from GtkTreeView which got deprecated. Let's see ;)


I understand that the application is very specific but hey...I use it daily and if it can help someone else, even better :)

Thank you once again for the feedback. 

Best regards :+1:
